@startuml
Nettleser -> Server: HTTP GET/
Server -> Database: JavaScript spør om data fra database
Database -> Server: Returner data
Server -> Server: JavaScript oppdaterer HTML \nslik at prosjekter blir lagt til
Server -> Nettleser: Sender HTML
Nettleser -> Server: HTTP GET /bilder/*.jpg \n (Spør om bilder til prosjektene om de eksisterer)
Server -> Nettleser: HTTP respons (sender bilder tilbake om de eksisterer)
Nettleser -> Server: HTTP GET /styles/style.css (spør om stilark)
Server -> Nettleser: HTTP respons (sender tilbake stilark)
Nettleser -> Server: HTTP GET /scripts/script.js \n(Spør om JavaScript filer)
Server -> Nettleser: Sender JavaScript filer tilbake.
@enduml