@startuml
Nettleser -> Server: Sender data om prosjektet med POST
Server -> Database: Validerer data \nog sender data til database for lagring
Database -> Server: Sender oppdatert informasjon tilbake
Server -> Server: Behandler data og oppretter ny artikkel med\ndata den fikk om nytt prosjekt
Server -> Nettleser: Sender HTTP statuskode tilbake
Nettleser -> Server: Nettleser refresher og \nspør om å få innholdet på nettsiden på nytt
Server -> Nettleser: Sender oppdatert innhold\nmed data om nytt prosjekt

@enduml
